### ISSUE TITLE
[BUG] Logging crashes script when no reads match the pattern

### ISSUE THREAD

**Issue by ggirelli** [ggirelli/fastx-barber#32]
```
Traceback (most recent call last):
  File "/home/gire/.local/bin/fbarber", line 8, in <module>
    sys.exit(main())
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.7/site-packages/fastx_barber/scripts/barber.py", line 45, in main
    args.run(args)
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.7/site-packages/fastx_barber/scripts/extract.py", line 336, in run
    f"({(n_matched-n_filtered)/n_matched*100:.2f}%)",
ZeroDivisionError: division by zero
```

**Comment by ggirelli** [comment]
Fixed in v0.1.1
