### ISSUE TITLE
[BUG] find_seq crash

### ISSUE THREAD

**Issue by ggirelli** [ggirelli/fastx-barber#87]
```bash
➜  reference fbarber find_seq Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz AAGCTT 
--case-insensitive --global-name --output Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.bed.gz
--log-file Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.log
[06/15/21 10:17:50] INFO     Log to                                                        scriptio.py:50
                             Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.log                  
                    INFO     General                                                      find_seq.py:111
                    INFO     Input                                                        find_seq.py:112
                             Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz                              
                    INFO     Needle          AAGCTT                                       find_seq.py:113
                    INFO     Output          Homo_sapiens.GRCh38.dna.primary_assembly.Hin find_seq.py:114
                             dIII_sites.bed.gz                                                           
                    INFO     Prefix          loc_                                         find_seq.py:115
                    INFO     Global          True                                         find_seq.py:116
Traceback (most recent call last):
  File "/home/gire/.local/bin/fbarber", line 8, in <module>
    sys.exit(main())
  File "/home/gire/.local/lib/python3.8/site-packages/fastx_barber/scripts/barber.py", line 45, in main
    args.run(args)
  File "/home/gire/.local/lib/python3.8/site-packages/fastx_barber/exception.py", line 14, in wrapper
    return fun(*args, **kwargs)
  File "/home/gire/.local/lib/python3.8/site-packages/fastx_barber/scripts/find_seq.py", line 125, in run
    record[1] = record[1].upper()
TypeError: 'tuple' object does not support item assignment
```

**Comment by ggirelli** [comment]
Fixed in `v0.1.4`
