### ISSUE TITLE
[BUG] find_seq crash with --case-insensitive option

### ISSUE THREAD

**Issue by ggirelli** [ggirelli/fastx-barber#89]
```bash
➜  gpseq-tutorial fbarber find_seq reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz AAGCTT 
--case-insensitive --global-name --output reference/Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.bed.gz
--log-file reference/Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.log
[06/15/21 10:51:22] INFO     Log to          reference/Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.log                                                                                    scriptio.py:50
                    INFO     General                                                                                                                                                                find_seq.py:111
                    INFO     Input           reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz                                                                                               find_seq.py:112
                    INFO     Needle          AAGCTT                                                                                                                                                 find_seq.py:113
                    INFO     Output          reference/Homo_sapiens.GRCh38.dna.primary_assembly.HindIII_sites.bed.gz                                                                                find_seq.py:114
                    INFO     Prefix          loc_                                                                                                                                                   find_seq.py:115
                    INFO     Global          True                                                                                                                                                   find_seq.py:116
Traceback (most recent call last):
  File "/home/gire/.local/bin/fbarber", line 8, in <module>
    sys.exit(main())
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.8/site-packages/fastx_barber/scripts/barber.py", line 45, in main
    args.run(args)
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.8/site-packages/fastx_barber/exception.py", line 14, in wrapper
    return fun(*args, **kwargs)
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.8/site-packages/fastx_barber/scripts/find_seq.py", line 126, in run
    for pos, location_id in search_needle(record, args.needle, location_id):
  File "/home/gire/.local/pipx/venvs/fastx-barber/lib/python3.8/site-packages/fastx_barber/match.py", line 221, in search_needle
    header, seq, _ = record
ValueError: not enough values to unpack (expected 3, got 2)
➜  gpseq-tutorial 

```

**Comment by ggirelli** [comment]
Fixed in `v0.1.5`.
